const countries = {
  "Afghanistan": "AF",
  "Albanien": "AL",
  "Algerien": "DZ",
  "Andorra": "AD",
  "Angola": "AO",
  "Antigua Und Barbuda": "AG",
  "Argentinien": "AR",
  "Armenien": "AM",
  "Australien": "AU",
  "Österreich": "AT",
  "Aserbaidschan": "AZ",
  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesch": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Belgien": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Bolivien": "BO",
  "Bosnien und Herzegowina": "BA",
  "Botswana": "BW",
  "Brasilien": "BR",
  "Brunei": "BN",
  "Bulgarien": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Kambodscha": "KH",
  "Kamerun": "CM",
  "Kanada": "CA",
  "Kap Verde": "CV",
  "Zentralafrikanische Republik": "CF",
  "Tschad": "TD",
  "Chile": "CL",
  "China": "CN",
  "Komoren": "KM",
  "Kolumbien": "CO",
  "Kongo": "CG",
  "Demokratische Republik Kongo": "CD",
  "Costa Rica": "CR",
  "Elfenbeinküste": "CI",
  "Kroatien": "HR",
  "Kuba": "CU",
  "Zypern": "CY",
  "Tschechien": "CZ",
  "Dänemark": "DK",
  "Dschibuti": "DJ",
  "Dominica": "DM",
  "Dominikanische Republik": "DO",
  "Ecuador": "EC",
  "Ägypten": "EG",
  "El Salvador": "SV",
  "Äquatorialguinea": "GQ",
  "Eritrea": "ER",
  "Estland": "EE",
  "Äthiopien": "ET",
  "Fidschii": "FJ",
  "Finnland": "FI",
  "Frankreich": "FR",
  "Gambia": "GM",
  "Georgien": "GE",
  "Deutschland": "DE",
  "Gabun": "GA",
  "Ghana": "GH",
  "Griechenland": "GR",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Haiti": "HT",
  "Vatikan": "VA",
  "Honduras": "HN",
  "Ungarn": "HU",
  "Island": "IS",
  "Indien": "IN",
  "Indonesien": "ID",
  "Iran": "IR",
  "Irak": "IQ",
  "Irland": "IE",
  "Israel": "IL",
  "Italien": "IT",
  "Jamaika": "JM",
  "Japan": "JP",
  "Jordanien": "JO",
  "Kasachstan": "KZ",
  "Kenia": "KE",
  "Kiribati": "KI",
  "Süd Korea": "KR",
  "Nord Korea": "KP",
  "Kuwait": "KW",
  "Kirgistan": "KG",
  "Laos": "LA",
  "Lettland": "LV",
  "Libanon": "LB",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libyen": "LY",
  "Liechtenstein": "LI",
  "Litauen": "LT",
  "Luxembourg": "LU",
  "Nord Mazedonien": "MK",
  "Madagaskar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Malediven": "MV",
  "Mali": "ML",
  "Malta": "MT",
  "Marshallinseln": "MH",
  "Mauretanien": "MR",
  "Mauritius": "MU",
  "Mexiko": "MX",
  "Mikronesien": "FM",
  "Moldau": "MD",
  "Monaco": "MC",
  "Mongolei": "MN",
  "Montenegro": "ME",
  "Marokko": "MA",
  "Mosambik": "MZ",
  "Myanmar": "MM",
  "Namibia": "NA",
  "Nauru": "NR",
  "Nepal": "NP",
  "Niederlande": "NL",
  "Neu Seeland": "NZ",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palau": "PW",
  "Panama": "PA",
  "Papua-Neuguinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippinen": "PH",
  "Polen": "PL",
  "Portugal": "PT",
  "Puerto Rico": "PR",
  "Katar": "QA",
  "Rumänien": "RO",
  "Russland": "RU",
  "Ruanda": "RW",
  "Saint Kitts Und Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent Und die Grenadinen": "VC",
  "Samoa": "WS",
  "San Marino": "SM",
  "Sao Tome Und Principe": "ST",
  "Saudi Arabia": "SA",
  "Senegal": "SN",
  "Serbien": "RS",
  "Seychellen": "SC",
  "Sierra Leone": "SL",
  "Singapur": "SG",
  "Slowakei": "SK",
  "Slowenien": "SI",
  "Salomonen": "SB",
  "Somalia": "SO",
  "South Afrika": "ZA",
  "Spanien": "ES",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Eswatini": "SZ",
  "Schweden": "SE",
  "Schweiz": "CH",
  "Syrien": "SY",
  "Tadschikistan": "TJ",
  "Tansania": "TZ",
  "Thailand": "TH",
  "Togo": "TG",
  "Osttimor": "TL",
  "Tonga": "TO",
  "Trinidad Und Tobago": "TT",
  "Tunesien": "TN",
  "Türkei": "TR",
  "Turkmenistan": "TM",
  "Tuvalu": "TV",
  "Uganda": "UG",
  "Ukraine": "UA",
  "Vereinigte Arabische Emirate": "AE",
  "Vereinigtes Königreich": "GB",
  "Vereinigte Staaten": "US",
  "Uruguay": "UY",
  "Usbekistan": "UZ",
  "Vanuatu": "VU",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "Jemen": "YE",
  "Sambia": "ZM",
  "Simbabwe": "ZW"
}

export default countries
